---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cgicloudnative/cfjump

inputs:
  - name: test-concourse-vault
  
run:
  path: concourse-vault-test/tasks/test-conconcourse-vault.sh